import { PrismaClient } from '@prisma/client';

import { env } from './env';

/**
 * Singleton Prisma client.
 *
 * NOTE: `@prisma/client` is generated by running `npm run prisma:generate`.
 * Until then, the import above will not resolve — this is expected on a fresh
 * checkout. See docs/SETUP.md.
 */
export const prisma = new PrismaClient({
  log: env.isDevelopment ? ['query', 'error', 'warn'] : ['error'],
});
